/* This file is automatically generated by configure.  Do not modify by hand. */
/* Define if compiling with the SDC-NTPCLOCK-MIB module files.  */
#define USING_SDC_NTPCLOCK_MIB_MODULE 1
 
/* Define if compiling with the default_modules module files.  */
#define USING_DEFAULT_MODULES_MODULE 1
 
/* Define if compiling with the if-mib module files.  */
#define USING_IF_MIB_MODULE 1
 
/* Define if compiling with the ip-mib module files.  */
#define USING_IP_MIB_MODULE 1
 
/* Define if compiling with the tcp-mib module files.  */
#define USING_TCP_MIB_MODULE 1
 
/* Define if compiling with the udp-mib module files.  */
#define USING_UDP_MIB_MODULE 1
 
/* Define if compiling with the SDC-NTPCLOCK-MIB/stsGroup/stsGroup module files.  */
#define USING_SDC_NTPCLOCK_MIB_STSGROUP_STSGROUP_MODULE 1
 
/* Define if compiling with the snmpv3mibs module files.  */
#define USING_SNMPV3MIBS_MODULE 1
 
/* Define if compiling with the mibII/snmp_mib module files.  */
#define USING_MIBII_SNMP_MIB_MODULE 1
 
/* Define if compiling with the mibII/system_mib module files.  */
#define USING_MIBII_SYSTEM_MIB_MODULE 1
 
/* Define if compiling with the mibII/sysORTable module files.  */
#define USING_MIBII_SYSORTABLE_MODULE 1
 
/* Define if compiling with the mibII/vacm_vars module files.  */
#define USING_MIBII_VACM_VARS_MODULE 1
 
/* Define if compiling with the if-mib/ifTable module files.  */
#define USING_IF_MIB_IFTABLE_MODULE 1
 
/* Define if compiling with the if-mib/ifXTable module files.  */
#define USING_IF_MIB_IFXTABLE_MODULE 1
 
/* Define if compiling with the ip-mib/ipAddressTable module files.  */
#define USING_IP_MIB_IPADDRESSTABLE_MODULE 1
 
/* Define if compiling with the ip-mib/ipAddressPrefixTable module files.  */
#define USING_IP_MIB_IPADDRESSPREFIXTABLE_MODULE 1
 
/* Define if compiling with the ip-mib/ipDefaultRouterTable module files.  */
#define USING_IP_MIB_IPDEFAULTROUTERTABLE_MODULE 1
 
/* Define if compiling with the ip-mib/inetNetToMediaTable module files.  */
#define USING_IP_MIB_INETNETTOMEDIATABLE_MODULE 1
 
/* Define if compiling with the ip-mib/ipSystemStatsTable module files.  */
#define USING_IP_MIB_IPSYSTEMSTATSTABLE_MODULE 1
 
/* Define if compiling with the ip-mib/ip_scalars module files.  */
#define USING_IP_MIB_IP_SCALARS_MODULE 1
 
/* Define if compiling with the ip-mib/ipv6ScopeZoneIndexTable module files.  */
#define USING_IP_MIB_IPV6SCOPEZONEINDEXTABLE_MODULE 1
 
/* Define if compiling with the ip-mib/ipIfStatsTable module files.  */
#define USING_IP_MIB_IPIFSTATSTABLE_MODULE 1
 
/* Define if compiling with the tcp-mib/tcpConnectionTable module files.  */
#define USING_TCP_MIB_TCPCONNECTIONTABLE_MODULE 1
 
/* Define if compiling with the tcp-mib/tcpListenerTable module files.  */
#define USING_TCP_MIB_TCPLISTENERTABLE_MODULE 1
 
/* Define if compiling with the udp-mib/udpEndpointTable module files.  */
#define USING_UDP_MIB_UDPENDPOINTTABLE_MODULE 1
 
/* Define if compiling with the config/semaphore module files.  */
#define USING_CONFIG_SEMAPHORE_MODULE 1
 
/* Define if compiling with the config/conf module files.  */
#define USING_CONFIG_CONF_MODULE 1
 
/* Define if compiling with the config/config module files.  */
#define USING_CONFIG_CONFIG_MODULE 1
 
/* Define if compiling with the snmpv3/snmpMPDStats_5_5 module files.  */
#define USING_SNMPV3_SNMPMPDSTATS_5_5_MODULE 1
 
/* Define if compiling with the snmpv3/usmStats_5_5 module files.  */
#define USING_SNMPV3_USMSTATS_5_5_MODULE 1
 
/* Define if compiling with the snmpv3/snmpEngine module files.  */
#define USING_SNMPV3_SNMPENGINE_MODULE 1
 
/* Define if compiling with the snmpv3/usmUser module files.  */
#define USING_SNMPV3_USMUSER_MODULE 1
 
/* Define if compiling with the mibII/updates module files.  */
#define USING_MIBII_UPDATES_MODULE 1
 
/* Define if compiling with the util_funcs module files.  */
#define USING_UTIL_FUNCS_MODULE 1
 
/* Define if compiling with the util_funcs/header_generic module files.  */
#define USING_UTIL_FUNCS_HEADER_GENERIC_MODULE 1
 
/* Define if compiling with the mibII/vacm_context module files.  */
#define USING_MIBII_VACM_CONTEXT_MODULE 1
 
/* Define if compiling with the if-mib/ifTable/ifTable module files.  */
#define USING_IF_MIB_IFTABLE_IFTABLE_MODULE 1
 
/* Define if compiling with the if-mib/ifXTable/ifXTable module files.  */
#define USING_IF_MIB_IFXTABLE_IFXTABLE_MODULE 1
 
/* Define if compiling with the ip-mib/ipAddressTable/ipAddressTable module files.  */
#define USING_IP_MIB_IPADDRESSTABLE_IPADDRESSTABLE_MODULE 1
 
/* Define if compiling with the ip-mib/ipAddressPrefixTable/ipAddressPrefixTable module files.  */
#define USING_IP_MIB_IPADDRESSPREFIXTABLE_IPADDRESSPREFIXTABLE_MODULE 1
 
/* Define if compiling with the ip-mib/ipDefaultRouterTable/ipDefaultRouterTable module files.  */
#define USING_IP_MIB_IPDEFAULTROUTERTABLE_IPDEFAULTROUTERTABLE_MODULE 1
 
/* Define if compiling with the ip-mib/data_access/arp module files.  */
#define USING_IP_MIB_DATA_ACCESS_ARP_MODULE 1
 
/* Define if compiling with the ip-mib/inetNetToMediaTable/inetNetToMediaTable module files.  */
#define USING_IP_MIB_INETNETTOMEDIATABLE_INETNETTOMEDIATABLE_MODULE 1
 
/* Define if compiling with the ip-mib/inetNetToMediaTable/inetNetToMediaTable_interface module files.  */
#define USING_IP_MIB_INETNETTOMEDIATABLE_INETNETTOMEDIATABLE_INTERFACE_MODULE 1
 
/* Define if compiling with the ip-mib/inetNetToMediaTable/inetNetToMediaTable_data_access module files.  */
#define USING_IP_MIB_INETNETTOMEDIATABLE_INETNETTOMEDIATABLE_DATA_ACCESS_MODULE 1
 
/* Define if compiling with the ip-mib/data_access/systemstats module files.  */
#define USING_IP_MIB_DATA_ACCESS_SYSTEMSTATS_MODULE 1
 
/* Define if compiling with the ip-mib/ipSystemStatsTable/ipSystemStatsTable module files.  */
#define USING_IP_MIB_IPSYSTEMSTATSTABLE_IPSYSTEMSTATSTABLE_MODULE 1
 
/* Define if compiling with the ip-mib/ipSystemStatsTable/ipSystemStatsTable_interface module files.  */
#define USING_IP_MIB_IPSYSTEMSTATSTABLE_IPSYSTEMSTATSTABLE_INTERFACE_MODULE 1
 
/* Define if compiling with the ip-mib/ipSystemStatsTable/ipSystemStatsTable_data_access module files.  */
#define USING_IP_MIB_IPSYSTEMSTATSTABLE_IPSYSTEMSTATSTABLE_DATA_ACCESS_MODULE 1
 
/* Define if compiling with the ip-mib/data_access/scalars_common module files.  */
#define USING_IP_MIB_DATA_ACCESS_SCALARS_COMMON_MODULE 1
 
/* Define if compiling with the ip-mib/ipv6ScopeZoneIndexTable/ipv6ScopeZoneIndexTable module files.  */
#define USING_IP_MIB_IPV6SCOPEZONEINDEXTABLE_IPV6SCOPEZONEINDEXTABLE_MODULE 1
 
/* Define if compiling with the ip-mib/ipIfStatsTable/ipIfStatsTable module files.  */
#define USING_IP_MIB_IPIFSTATSTABLE_IPIFSTATSTABLE_MODULE 1
 
/* Define if compiling with the ip-mib/ipIfStatsTable/ipIfStatsTable_interface module files.  */
#define USING_IP_MIB_IPIFSTATSTABLE_IPIFSTATSTABLE_INTERFACE_MODULE 1
 
/* Define if compiling with the ip-mib/ipIfStatsTable/ipIfStatsTable_data_access module files.  */
#define USING_IP_MIB_IPIFSTATSTABLE_IPIFSTATSTABLE_DATA_ACCESS_MODULE 1
 
/* Define if compiling with the tcp-mib/data_access/tcpConn module files.  */
#define USING_TCP_MIB_DATA_ACCESS_TCPCONN_MODULE 1
 
/* Define if compiling with the tcp-mib/tcpConnectionTable/tcpConnectionTable module files.  */
#define USING_TCP_MIB_TCPCONNECTIONTABLE_TCPCONNECTIONTABLE_MODULE 1
 
/* Define if compiling with the tcp-mib/tcpListenerTable/tcpListenerTable module files.  */
#define USING_TCP_MIB_TCPLISTENERTABLE_TCPLISTENERTABLE_MODULE 1
 
/* Define if compiling with the udp-mib/udpEndpointTable/udpEndpointTable module files.  */
#define USING_UDP_MIB_UDPENDPOINTTABLE_UDPENDPOINTTABLE_MODULE 1
 
/* Define if compiling with the util_funcs/header_simple_table module files.  */
#define USING_UTIL_FUNCS_HEADER_SIMPLE_TABLE_MODULE 1
 
/* Define if compiling with the if-mib/data_access/interface module files.  */
#define USING_IF_MIB_DATA_ACCESS_INTERFACE_MODULE 1
 
/* Define if compiling with the if-mib/ifTable/ifTable_interface module files.  */
#define USING_IF_MIB_IFTABLE_IFTABLE_INTERFACE_MODULE 1
 
/* Define if compiling with the if-mib/ifTable/ifTable_data_access module files.  */
#define USING_IF_MIB_IFTABLE_IFTABLE_DATA_ACCESS_MODULE 1
 
/* Define if compiling with the if-mib/ifXTable/ifXTable_interface module files.  */
#define USING_IF_MIB_IFXTABLE_IFXTABLE_INTERFACE_MODULE 1
 
/* Define if compiling with the if-mib/ifXTable/ifXTable_data_access module files.  */
#define USING_IF_MIB_IFXTABLE_IFXTABLE_DATA_ACCESS_MODULE 1
 
/* Define if compiling with the ip-mib/data_access/ipaddress module files.  */
#define USING_IP_MIB_DATA_ACCESS_IPADDRESS_MODULE 1
 
/* Define if compiling with the ip-mib/ipAddressTable/ipAddressTable_interface module files.  */
#define USING_IP_MIB_IPADDRESSTABLE_IPADDRESSTABLE_INTERFACE_MODULE 1
 
/* Define if compiling with the ip-mib/ipAddressTable/ipAddressTable_data_access module files.  */
#define USING_IP_MIB_IPADDRESSTABLE_IPADDRESSTABLE_DATA_ACCESS_MODULE 1
 
/* Define if compiling with the ip-mib/ipAddressPrefixTable/ipAddressPrefixTable_interface module files.  */
#define USING_IP_MIB_IPADDRESSPREFIXTABLE_IPADDRESSPREFIXTABLE_INTERFACE_MODULE 1
 
/* Define if compiling with the ip-mib/ipAddressPrefixTable/ipAddressPrefixTable_data_access module files.  */
#define USING_IP_MIB_IPADDRESSPREFIXTABLE_IPADDRESSPREFIXTABLE_DATA_ACCESS_MODULE 1
 
/* Define if compiling with the ip-mib/data_access/defaultrouter module files.  */
#define USING_IP_MIB_DATA_ACCESS_DEFAULTROUTER_MODULE 1
 
/* Define if compiling with the ip-mib/ipDefaultRouterTable/ipDefaultRouterTable_interface module files.  */
#define USING_IP_MIB_IPDEFAULTROUTERTABLE_IPDEFAULTROUTERTABLE_INTERFACE_MODULE 1
 
/* Define if compiling with the ip-mib/ipDefaultRouterTable/ipDefaultRouterTable_data_access module files.  */
#define USING_IP_MIB_IPDEFAULTROUTERTABLE_IPDEFAULTROUTERTABLE_DATA_ACCESS_MODULE 1
 
/* Define if compiling with the ip-mib/ipDefaultRouterTable/ipDefaultRouterTable_data_get module files.  */
#define USING_IP_MIB_IPDEFAULTROUTERTABLE_IPDEFAULTROUTERTABLE_DATA_GET_MODULE 1
 
/* Define if compiling with the ip-mib/data_access/arp_common module files.  */
#define USING_IP_MIB_DATA_ACCESS_ARP_COMMON_MODULE 1
 
/* Define if compiling with the ip-mib/data_access/arp_netlink module files.  */
#define USING_IP_MIB_DATA_ACCESS_ARP_NETLINK_MODULE 1
 
/* Define if compiling with the ip-mib/data_access/systemstats_common module files.  */
#define USING_IP_MIB_DATA_ACCESS_SYSTEMSTATS_COMMON_MODULE 1
 
/* Define if compiling with the ip-mib/data_access/systemstats_linux module files.  */
#define USING_IP_MIB_DATA_ACCESS_SYSTEMSTATS_LINUX_MODULE 1
 
/* Define if compiling with the ip-mib/data_access/scalars_linux module files.  */
#define USING_IP_MIB_DATA_ACCESS_SCALARS_LINUX_MODULE 1
 
/* Define if compiling with the ip-mib/data_access/ipv6scopezone module files.  */
#define USING_IP_MIB_DATA_ACCESS_IPV6SCOPEZONE_MODULE 1
 
/* Define if compiling with the ip-mib/ipv6ScopeZoneIndexTable/ipv6ScopeZoneIndexTable_interface module files.  */
#define USING_IP_MIB_IPV6SCOPEZONEINDEXTABLE_IPV6SCOPEZONEINDEXTABLE_INTERFACE_MODULE 1
 
/* Define if compiling with the ip-mib/ipv6ScopeZoneIndexTable/ipv6ScopeZoneIndexTable_data_access module files.  */
#define USING_IP_MIB_IPV6SCOPEZONEINDEXTABLE_IPV6SCOPEZONEINDEXTABLE_DATA_ACCESS_MODULE 1
 
/* Define if compiling with the ip-mib/ipIfStatsTable/ipIfStatsTable_data_get module files.  */
#define USING_IP_MIB_IPIFSTATSTABLE_IPIFSTATSTABLE_DATA_GET_MODULE 1
 
/* Define if compiling with the tcp-mib/data_access/tcpConn_common module files.  */
#define USING_TCP_MIB_DATA_ACCESS_TCPCONN_COMMON_MODULE 1
 
/* Define if compiling with the tcp-mib/data_access/tcpConn_linux module files.  */
#define USING_TCP_MIB_DATA_ACCESS_TCPCONN_LINUX_MODULE 1
 
/* Define if compiling with the util_funcs/get_pid_from_inode module files.  */
#define USING_UTIL_FUNCS_GET_PID_FROM_INODE_MODULE 1
 
/* Define if compiling with the tcp-mib/tcpConnectionTable/tcpConnectionTable_interface module files.  */
#define USING_TCP_MIB_TCPCONNECTIONTABLE_TCPCONNECTIONTABLE_INTERFACE_MODULE 1
 
/* Define if compiling with the tcp-mib/tcpConnectionTable/tcpConnectionTable_data_access module files.  */
#define USING_TCP_MIB_TCPCONNECTIONTABLE_TCPCONNECTIONTABLE_DATA_ACCESS_MODULE 1
 
/* Define if compiling with the tcp-mib/tcpListenerTable/tcpListenerTable_interface module files.  */
#define USING_TCP_MIB_TCPLISTENERTABLE_TCPLISTENERTABLE_INTERFACE_MODULE 1
 
/* Define if compiling with the tcp-mib/tcpListenerTable/tcpListenerTable_data_access module files.  */
#define USING_TCP_MIB_TCPLISTENERTABLE_TCPLISTENERTABLE_DATA_ACCESS_MODULE 1
 
/* Define if compiling with the udp-mib/data_access/udp_endpoint module files.  */
#define USING_UDP_MIB_DATA_ACCESS_UDP_ENDPOINT_MODULE 1
 
/* Define if compiling with the udp-mib/udpEndpointTable/udpEndpointTable_interface module files.  */
#define USING_UDP_MIB_UDPENDPOINTTABLE_UDPENDPOINTTABLE_INTERFACE_MODULE 1
 
/* Define if compiling with the udp-mib/udpEndpointTable/udpEndpointTable_data_access module files.  */
#define USING_UDP_MIB_UDPENDPOINTTABLE_UDPENDPOINTTABLE_DATA_ACCESS_MODULE 1
 
/* Define if compiling with the if-mib/data_access/interface_linux module files.  */
#define USING_IF_MIB_DATA_ACCESS_INTERFACE_LINUX_MODULE 1
 
/* Define if compiling with the if-mib/data_access/interface_ioctl module files.  */
#define USING_IF_MIB_DATA_ACCESS_INTERFACE_IOCTL_MODULE 1
 
/* Define if compiling with the ip-mib/data_access/ipaddress_common module files.  */
#define USING_IP_MIB_DATA_ACCESS_IPADDRESS_COMMON_MODULE 1
 
/* Define if compiling with the ip-mib/data_access/ipaddress_linux module files.  */
#define USING_IP_MIB_DATA_ACCESS_IPADDRESS_LINUX_MODULE 1
 
/* Define if compiling with the ip-mib/data_access/defaultrouter_common module files.  */
#define USING_IP_MIB_DATA_ACCESS_DEFAULTROUTER_COMMON_MODULE 1
 
/* Define if compiling with the ip-mib/data_access/defaultrouter_linux module files.  */
#define USING_IP_MIB_DATA_ACCESS_DEFAULTROUTER_LINUX_MODULE 1
 
/* Define if compiling with the ip-mib/data_access/ipv6scopezone_common module files.  */
#define USING_IP_MIB_DATA_ACCESS_IPV6SCOPEZONE_COMMON_MODULE 1
 
/* Define if compiling with the ip-mib/data_access/ipv6scopezone_linux module files.  */
#define USING_IP_MIB_DATA_ACCESS_IPV6SCOPEZONE_LINUX_MODULE 1
 
/* Define if compiling with the udp-mib/data_access/udp_endpoint_common module files.  */
#define USING_UDP_MIB_DATA_ACCESS_UDP_ENDPOINT_COMMON_MODULE 1
 
/* Define if compiling with the udp-mib/data_access/udp_endpoint_linux module files.  */
#define USING_UDP_MIB_DATA_ACCESS_UDP_ENDPOINT_LINUX_MODULE 1
 
/* Define if compiling with the ip-mib/data_access/ipaddress_ioctl module files.  */
#define USING_IP_MIB_DATA_ACCESS_IPADDRESS_IOCTL_MODULE 1
 
